apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: trigger1
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret-combined-app1
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: trigger-app1
  template:
    ref: trigger-app1
